num_tokens: 8192 
vae: evqvae
ch_mult: [1,2,4]
attn_resolutions: [16]
resolution: 64
img_size: 64
p_loss_weight: 0.1
loss_img_weight: 1.0
#finetuned: True
loss_type: lpips_l2
vae_path: 'pretrained/cmota_vae_traeind_200.ckpt'
backup: False
truncate_captions: True
web_dataset: False
gpus: 8
num_workers: 16
train_dir: 'dataset/dalle_dataset/pororo'
dataset_size: [15566, 500]
image_log_steps: 500
lr_decay: True
depth: 12
heads: 16
text_seq_len: 80
epoch: 200
batch_size: 8
save_step_frequency: 200
hybrid_mask: True
output_imgs_dir: 'output_imgs/test'
n_memory_cells: 1
load_images: False
memory: True
gru_updater: False
special_case_img_seq_len: True
bidirection: True